### ISSUE TITLE
get() does not support git

### ISSUE THREAD

**Issue by mitchweaver** [bonsai-linux/bonsai#6]
This is low priority due to any use of `git` requiring git as a dependency which is unideal. You should always try to use tarballs instead.

... With that said, I know some people will still want git for "bleeding edge", so it would be nice to add.

**Comment by trvv** [comment]
`git` could be supported through an extension to the package manager itself... like some kind of plugin system? because how it's referenced in the source, checking a tarball release from github won't be supported across different hosting solutions. Maybe write a small C program to do git cloning instead of doing the whole thing?

**Comment by mitchweaver** [comment]
> checking a tarball release from github won't be supported across different hosting solutions

You're just curling a tarball, what's not to be supported?

> Maybe write a small C program to do git cloning

Or just use `git`?

It would (very roughly) look something like this:

```bash
if [ "$version" = git ] ; then
    if [ -d "$name" ] ; then
        cd "$name" ; git reset ; git pull
    else
        git clone "$source"
    fi
else
    # we're using curl
fi
```
